INSERT INTO medicine (name, type, description, price, currency, prescription_needed, is_available) VALUES
('Paracetamol', 1, 'Used to relieve pain and reduce fever.', 4.99, 'EUR', FALSE, TRUE),
('Ibuprofen', 1, 'Anti-inflammatory medication used to reduce pain and swelling.', 5.49, 'EUR', FALSE, TRUE),
('Aspirin', 1, 'Pain reliever, fever reducer, and anti-inflammatory medication.', 3.99, 'EUR', FALSE, TRUE),
('Amoxicillin', 2, 'Antibiotic used to treat bacterial infections.', 12.99, 'EUR', TRUE, TRUE),
('Metformin', 3, 'Medication used to treat type 2 diabetes.', 8.99, 'EUR', TRUE, TRUE),
('Omeprazole', 4, 'Medication used to treat acid reflux and stomach ulcers.', 6.99, 'EUR', TRUE, TRUE),
('Lisinopril', 5, 'Medication used to treat high blood pressure.', 7.49, 'EUR', TRUE, TRUE),
('Simvastatin', 6, 'Medication used to lower cholesterol.', 9.99, 'EUR', TRUE, TRUE),
('Atorvastatin', 6, 'Medication used to lower cholesterol and triglycerides.', 11.49, 'EUR', TRUE, TRUE),
('Losartan', 5, 'Medication used to treat high blood pressure and kidney disease.', 10.99, 'EUR', TRUE, TRUE),
('Amlodipine', 5, 'Medication used to treat high blood pressure and chest pain.', 8.49, 'EUR', TRUE, TRUE),
('Levothyroxine', 3, 'Medication used to treat hypothyroidism.', 4.49, 'EUR', TRUE, TRUE),
('Metoprolol', 5, 'Medication used to treat high blood pressure and chest pain.', 7.99, 'EUR', TRUE, TRUE),
('Furosemide', 8, 'Diuretic medication used to reduce fluid retention.', 5.99, 'EUR', TRUE, TRUE),
('Gabapentin', 9, 'Medication used to treat nerve pain and seizures.', 14.99, 'EUR', TRUE, TRUE),
('Sertraline', 1, 'Antidepressant medication used to treat depression and anxiety.', 10.49, 'EUR', TRUE, TRUE),
('Prednisone', 1, 'Corticosteroid medication used to treat inflammation.', 6.49, 'EUR', TRUE, TRUE),
('Tramadol', 1, 'Pain reliever used to treat moderate to severe pain.', 9.49, 'EUR', TRUE, TRUE),
('Clopidogrel', 1, 'Antiplatelet medication used to prevent blood clots.', 13.99, 'EUR', TRUE, TRUE),
('Albuterol', 1, 'Medication used to treat asthma and other breathing conditions.', 12.49, 'EUR', TRUE, TRUE),
('Cetirizine', 6, 'Antihistamine used to treat allergy symptoms.', 5.49, 'EUR', FALSE, TRUE),
('Meloxicam', 1, 'Anti-inflammatory medication used to treat arthritis.', 8.99, 'EUR', TRUE, TRUE),
('Lorazepam', 1, 'Medication used to treat anxiety disorders.', 15.49, 'EUR', TRUE, TRUE),
('Pantoprazole', 4, 'Medication used to treat acid reflux and stomach ulcers.', 11.99, 'EUR', TRUE, TRUE),
('Loratadine', 6, 'Antihistamine used to treat allergy symptoms.', 6.99, 'EUR', FALSE, TRUE),
('Naproxen', 1, 'Anti-inflammatory medication used to reduce pain and swelling.', 7.49, 'EUR', FALSE, TRUE),
('Fluoxetine', 1, 'Antidepressant medication used to treat depression and anxiety.', 10.99, 'EUR', TRUE, TRUE),
('Venlafaxine', 1, 'Antidepressant medication used to treat depression and anxiety.', 12.99, 'EUR', TRUE, TRUE),
('Citalopram', 1, 'Antidepressant medication used to treat depression and anxiety.', 9.99, 'EUR', TRUE, TRUE),
('Escitalopram', 1, 'Antidepressant medication used to treat depression and anxiety.', 11.49, 'EUR', TRUE, TRUE),
('Azithromycin', 2, 'Antibiotic used to treat bacterial infections.', 14.49, 'EUR', TRUE, TRUE),
('Hydrochlorothiazide', 8, 'Diuretic medication used to treat high blood pressure.', 6.49, 'EUR', TRUE, TRUE),
('Trazodone', 1, 'Antidepressant medication used to treat depression and anxiety.', 8.49, 'EUR', TRUE, TRUE),
('Warfarin', 1, 'Anticoagulant medication used to prevent blood clots.', 9.49, 'EUR', TRUE, TRUE),
('Doxycycline', 2, 'Antibiotic used to treat bacterial infections.', 12.99, 'EUR', TRUE, TRUE),
('Cyclobenzaprine', 8, 'Muscle relaxant used to treat muscle spasms.', 7.99, 'EUR', TRUE, TRUE),
('Hydrocortisone', 1, 'Topical corticosteroid used to treat skin inflammation.', 5.99, 'EUR', FALSE, TRUE),
('Clindamycin', 2, 'Antibiotic used to treat bacterial infections.', 13.49, 'EUR', TRUE, TRUE),
('Carvedilol', 5, 'Medication used to treat high blood pressure and heart failure.', 9.99, 'EUR', TRUE, TRUE),
('Atenolol', 5, 'Medication used to treat high blood pressure and chest pain.', 7.49, 'EUR', TRUE, TRUE),
('Propranolol', 5, 'Medication used to treat high blood pressure and anxiety.', 8.99, 'EUR', TRUE, TRUE),
('Valsartan', 5, 'Medication used to treat high blood pressure and heart failure.', 11.49, 'EUR', TRUE, TRUE),
('Rosuvastatin', 6, 'Medication used to lower cholesterol and triglycerides.', 12.49, 'EUR', TRUE, TRUE),
('Oxycodone', 1, 'Pain reliever used to treat moderate to severe pain.', 15.99, 'EUR', TRUE, TRUE),
('Fexofenadine', 6, 'Antihistamine used to treat allergy symptoms.', 6.49, 'EUR', FALSE, TRUE),
('Tamsulosin', 1, 'Medication used to treat urinary retention and enlarged prostate.', 9.49, 'EUR', TRUE, TRUE);